services:
  worker-1:
    build:
      context: ..
      dockerfile: hpc-engine/Dockerfile
    environment:
      - PORT=50051
      - NODE_ID=worker-1
    networks:
      - pipeline-net
      - s4t-bridge

  worker-2:
    build:
      context: ..
      dockerfile: hpc-engine/Dockerfile
    environment:
      - PORT=50051
      - NODE_ID=worker-2
    networks:
      - pipeline-net
      - s4t-bridge

  worker-3:
    build:
      context: ..
      dockerfile: hpc-engine/Dockerfile
    environment:
      - PORT=50051
      - NODE_ID=worker-3
    networks:
      - pipeline-net
      - s4t-bridge

  satellite:
    build:
      context: ..
      dockerfile: satellite/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - WORKER_NODES=worker-1:50051,worker-2:50051,worker-3:50051
    networks:
      - pipeline-net
      - s4t-bridge
    depends_on:
      - worker-1
      - worker-2
      - worker-3

networks:
  pipeline-net:
    driver: bridge
  s4t-bridge:
    external: true
