services:
  worker-1:
    build:
      context: ..
      dockerfile: hpc-engine/Dockerfile
    environment:
      - PORT=50051
      - NODE_ID=worker-1
    networks:
      - pipeline-net
      - s4t-bridge

  worker-2:
    build:
      context: ..
      dockerfile: hpc-engine/Dockerfile
    environment:
      - PORT=50051
      - NODE_ID=worker-2
    networks:
      - pipeline-net
      - s4t-bridge

  worker-3:
    build:
      context: ..
      dockerfile: hpc-engine/Dockerfile
    environment:
      - PORT=50051
      - NODE_ID=worker-3
    networks:
      - pipeline-net
      - s4t-bridge

  satellite:
    build:
      context: ..
      dockerfile: satellite/Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - GATEWAY_URL=http://gateway:8000
      - IOTRONIC_URL=http://iotronic-conductor:8812
      - PLUGIN_NAME=grpc_client
    networks:
      - pipeline-net
      - s4t-bridge
      - stack4things_dockercompose_deployment_s4t
    depends_on:
      - worker-1
      - worker-2
      - worker-3

networks:
  pipeline-net:
    driver: bridge
  s4t-bridge:
    external: true
  stack4things_dockercompose_deployment_s4t:
    external: true
