/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OnboardingTrust } from "./OnboardingTrust";
export * as factories from "./factories";
export { OnboardingTrust__factory } from "./factories/OnboardingTrust__factory";
