/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface OnboardingTrustInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approve"
      | "nextRequestId"
      | "reject"
      | "requestOnboarding"
      | "requests"
      | "revoke"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OnboardingApproved"
      | "OnboardingRejected"
      | "OnboardingRequested"
      | "OnboardingRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextRequestId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestOnboarding",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revoke",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestOnboarding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
}

export namespace OnboardingApprovedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    deviceId: string,
    owner: AddressLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    deviceId: string,
    owner: string
  ];
  export interface OutputObject {
    requestId: bigint;
    deviceId: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OnboardingRejectedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    deviceId: string,
    owner: AddressLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    deviceId: string,
    owner: string
  ];
  export interface OutputObject {
    requestId: bigint;
    deviceId: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OnboardingRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    deviceId: string,
    requester: AddressLike,
    owner: AddressLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    deviceId: string,
    requester: string,
    owner: string
  ];
  export interface OutputObject {
    requestId: bigint;
    deviceId: string;
    requester: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OnboardingRevokedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    deviceId: string,
    revoker: AddressLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    deviceId: string,
    revoker: string
  ];
  export interface OutputObject {
    requestId: bigint;
    deviceId: string;
    revoker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OnboardingTrust extends BaseContract {
  connect(runner?: ContractRunner | null): OnboardingTrust;
  waitForDeployment(): Promise<this>;

  interface: OnboardingTrustInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approve: TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;

  nextRequestId: TypedContractMethod<[], [bigint], "view">;

  reject: TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;

  requestOnboarding: TypedContractMethod<
    [deviceId: string, owner: AddressLike],
    [bigint],
    "nonpayable"
  >;

  requests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        deviceId: string;
        requester: string;
        owner: string;
        status: bigint;
      }
    ],
    "view"
  >;

  revoke: TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextRequestId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reject"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestOnboarding"
  ): TypedContractMethod<
    [deviceId: string, owner: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        deviceId: string;
        requester: string;
        owner: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "OnboardingApproved"
  ): TypedContractEvent<
    OnboardingApprovedEvent.InputTuple,
    OnboardingApprovedEvent.OutputTuple,
    OnboardingApprovedEvent.OutputObject
  >;
  getEvent(
    key: "OnboardingRejected"
  ): TypedContractEvent<
    OnboardingRejectedEvent.InputTuple,
    OnboardingRejectedEvent.OutputTuple,
    OnboardingRejectedEvent.OutputObject
  >;
  getEvent(
    key: "OnboardingRequested"
  ): TypedContractEvent<
    OnboardingRequestedEvent.InputTuple,
    OnboardingRequestedEvent.OutputTuple,
    OnboardingRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OnboardingRevoked"
  ): TypedContractEvent<
    OnboardingRevokedEvent.InputTuple,
    OnboardingRevokedEvent.OutputTuple,
    OnboardingRevokedEvent.OutputObject
  >;

  filters: {
    "OnboardingApproved(uint256,string,address)": TypedContractEvent<
      OnboardingApprovedEvent.InputTuple,
      OnboardingApprovedEvent.OutputTuple,
      OnboardingApprovedEvent.OutputObject
    >;
    OnboardingApproved: TypedContractEvent<
      OnboardingApprovedEvent.InputTuple,
      OnboardingApprovedEvent.OutputTuple,
      OnboardingApprovedEvent.OutputObject
    >;

    "OnboardingRejected(uint256,string,address)": TypedContractEvent<
      OnboardingRejectedEvent.InputTuple,
      OnboardingRejectedEvent.OutputTuple,
      OnboardingRejectedEvent.OutputObject
    >;
    OnboardingRejected: TypedContractEvent<
      OnboardingRejectedEvent.InputTuple,
      OnboardingRejectedEvent.OutputTuple,
      OnboardingRejectedEvent.OutputObject
    >;

    "OnboardingRequested(uint256,string,address,address)": TypedContractEvent<
      OnboardingRequestedEvent.InputTuple,
      OnboardingRequestedEvent.OutputTuple,
      OnboardingRequestedEvent.OutputObject
    >;
    OnboardingRequested: TypedContractEvent<
      OnboardingRequestedEvent.InputTuple,
      OnboardingRequestedEvent.OutputTuple,
      OnboardingRequestedEvent.OutputObject
    >;

    "OnboardingRevoked(uint256,string,address)": TypedContractEvent<
      OnboardingRevokedEvent.InputTuple,
      OnboardingRevokedEvent.OutputTuple,
      OnboardingRevokedEvent.OutputObject
    >;
    OnboardingRevoked: TypedContractEvent<
      OnboardingRevokedEvent.InputTuple,
      OnboardingRevokedEvent.OutputTuple,
      OnboardingRevokedEvent.OutputObject
    >;
  };
}
